@startuml ユースケース図
left to right direction
actor 利用者
actor ホテル従業員
actor ホテル管理者

rectangle ホテル予約システム {
    usecase 空室状況を閲覧する
    usecase (<u>ホテルの部屋を予約する</u>\n拡張点\nキャンペーン期間中) as ホテルの部屋を予約する
    usecase 空室状況を入力する
    usecase 予約を集計する
    usecase ログインする
    usecase 会員登録する
    usecase 宿泊費がキャンペーン価格になる
}

利用者 --> 空室状況を閲覧する
利用者 --> ホテルの部屋を予約する
ホテル従業員 --> 空室状況を入力する
ホテル管理者 --> 予約を集計する
ホテルの部屋を予約する .> ログインする : << include >>
ログインする .> 会員登録する : << include >>
空室状況を入力する .> ログインする : << include >>
予約を集計する .> ログインする : << include >>
宿泊費がキャンペーン価格になる .> ホテルの部屋を予約する : << extend >>

@enduml