@startuml
[*] --> メニュー : 予約システムに接続
メニュー --> 予約と確認
予約と確認 --> あなたの順番 : 登録ボタンを押す[名前と電話番号を入力する]
予約と確認 --> あなたの順番 : 確認ボタンを押す[名前か電話番号を入力する]
あなたの順番 --> メニュー
予約と確認 --> メニュー : 取消ボタンを押す[名前か電話番号を入力する]
メニュー --> 今の順番
今の順番 --> メニュー
メニュー --> [*]