@startuml
actor 患者
actor 看護師
rectangle c{
    usecase 予約をする
    usecase 順番を確認する
    usecase 順番を取り消す
    usecase 現在診察中の患者の順番を表示する
    usecase 現在の患者番号を1つ増やす
}
患者 --> 予約をする
患者 --> 順番を確認する
患者 --> 順番を取り消す
患者 --> 現在診察中の患者の順番を表示する
看護師 --> 現在の患者番号を1つ増やす