@startumlleft 故郷に水を届けるんや
left to right direction
actor 申請者 #DDDDDD;line:black;line.bold;
actor 承認者 #DDDDDD;line:black;line.bold;
actor 経理担当者 #DDDDDD;line:black;line.bold;
actor 交通費精算システム #DDDDDD;line:black;line.bold;
rectangle 出張申請システム {
usecase 出張申請を登録する AS 登録
usecase 出張申請を提出する AS 提出
usecase 出張申請を承認する AS 承認
usecase 出張申請を却下する AS 却下
usecase 出張申請を指し戻す AS 差し戻し
usecase 出張申請を確認する AS 確認
}
申請者 --> 登録
申請者 --> 提出
承認者 --> 承認
承認者 --> 却下
承認者 --> 差し戻し
承認者 --> 確認
経理担当者 --> 確認
登録 <-- 交通費精算システム
@enduml